version: '3.8'

services:
  peercrypt:
    build:
      context: .
      dockerfile: Dockerfile
    image: peercrypt:latest
    container_name: peercrypt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      - GOSSIP_INTERVAL=5.0
      - DEFAULT_MODE=aimd
    command: src/cli.py --host 0.0.0.0 --port 5000 --gossip-interval ${GOSSIP_INTERVAL} --mode ${DEFAULT_MODE} 